name: Release Patch Version

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Prepare java
        uses: actions/setup-java@v5
        with:
          distribution: adopt
          java-version: 21

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.5
        with:
          lein: latest



      - name: Configure GPG key
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        run: echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import >/dev/null 2>/dev/null

      - name: Step patch version for release
        run: lein bump patch

      - name: Step bump sub project dependency versions
        run: lein sub-bump

      - name: Step version in README.md
        run: lein bump-md

      - name: Run lein sub install
        run: lein sub install

      - name: Run lein install
        run: lein install

      - name: Run sub lein test
        run: lein sub test

      - name: Run lein test
        run: lein test

      - name: Push version bump
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Stepping project version to prepare it for release

      - name: Add git tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: lein git-tag


      - name: Deploy to clojars
        env:
          CLOJARS_USER: ${{ secrets.CLOJARS_USER }}
          BOA_PARENT_CLOJARS_PASS: ${{ secrets.BOA_PARENT_CLOJARS_PASS }}
          BOA_QUERY_CLOJARS_PASS: ${{ secrets.BOA_QUERY_CLOJARS_PASS }}
          BOA_SQL_CLOJARS_PASS: ${{ secrets.BOA_SQL_CLOJARS_PASS }}
          NEXT_JDBC_ADAPTER_CLOJARS_PASS: ${{ secrets.NEXT_JDBC_ADAPTER_CLOJARS_PASS }}
        run: lein sub deploy clojars

      - name: Bump project version to snapshot
        run: lein bump dev

      - name: Step bump sub project dependency versions
        run: lein sub-bump

      - name: Push snapshot bump
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Stepping project version for the next development cycle
